version: '3.8'

services:
  backend:
    image: tmdung0910/mern-backend:1.0 # Câu 51
    ports:
      - "5000:5000"                              # Câu 53
    environment:
      - MONGODB_URI=mongodb+srv://dung0856028347_db_user:xWk1WpYWZiZIVFNc@tmd0910.mey6m6i.mongodb.net/cloud_lab?appName=TMD0910 # Câu 55
      - PORT=5000
    restart: always

  frontend:
    image: tmdung0910/mern-frontend:1.0 # Câu 52
    ports:
      - "3000:3000"                              # Câu 54 
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    restart: always